name: Build

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'README*'
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11

    - name: Get Date
      id: get-date
      run: |
        echo "::set-output name=date::$(/bin/date -u "+%Y-%m")"
      shell: bash
    - name: Cache Maven Repository
      id: cache-maven
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        # refresh cache every month to avoid unlimited growth
        key: maven-repo-${{ steps.get-date.outputs.date }}

    - name: Build with Maven
      run: mvn -B formatter:validate verify --file pom.xml -Dnative

    - name: Delete Quarkiverse Artifacts From Cache
      shell: bash
      run: rm -rf ~/.m2/repository/io/quarkiverse
